<a href="https://colab.research.google.com/github/sgr1118/FD/blob/main/FD19_Deep_learning_layer(2)_(220804).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 19-3. 단어를 부탁해! Embedding 레이어
# 원-핫 벡터 생성
import tensorflow as tf

vocab = {      # 사용할 단어 사전 정의
    "i": 0,
    "need": 1,
    "some": 2,
    "more": 3,
    "coffee": 4,
    "cake": 5,
    "cat": 6,
    "dog": 7}

sentence = 'i i i i need some more coffee coffee coffee'
# 위 sentence
_input = [vocab[w] for w in sentence.split()]  # [0, 0, 0, 0, 1, 2, 3, 4, 4, 4]

vocab_size = len(vocab)

one_hot = tf.one_hot(_input, vocab_size)
print(one_hot.numpy())

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]


In [ ]:
# Linear 레이어에 원-핫 벡터를 넣어보기
distribution_size = 2 # 2차원으로 분산 표현
linear = tf.keras.layers.Dense(units=distribution_size, use_bias=False)
one_hot_linear = linear(one_hot)

print("Linear Weight")
print(linear.weights[0].numpy())

print("\nOne-Hot Linear Result")
print(one_hot_linear.numpy())

Linear Weight
[[ 0.44856846 -0.32948077]
 [-0.22136456 -0.15440005]
 [ 0.3260082  -0.27210563]
 [-0.7019764   0.09530932]
 [-0.47168928  0.5753845 ]
 [ 0.17575365 -0.6628198 ]
 [ 0.7413982   0.7616451 ]
 [ 0.12514794 -0.74043435]]

One-Hot Linear Result
[[ 0.44856846 -0.32948077]
 [ 0.44856846 -0.32948077]
 [ 0.44856846 -0.32948077]
 [ 0.44856846 -0.32948077]
 [-0.22136456 -0.15440005]
 [ 0.3260082  -0.27210563]
 [-0.7019764   0.09530932]
 [-0.47168928  0.5753845 ]
 [-0.47168928  0.5753845 ]
 [-0.47168928  0.5753845 ]]


In [ ]:
# Embedding 레이어의 입력으로 넣어주는 처리
some_words = tf.constant([[3, 57, 35]])
# 3번 단어 / 57번 단어 / 35번 단어로 이루어진 한 문장입니다.

print("Embedding을 진행할 문장:", some_words.shape)
embedding_layer = tf.keras.layers.Embedding(input_dim=64, output_dim=100)
# 총 64개의 단어를 포함한 Embedding 레이어를 선언할 것이고,
# 각 단어는 100차원으로 분산 표현 할 것입니다.

print("Embedding된 문장:", embedding_layer(some_words).shape)
print("Embedding Layer의 Weight 형태:", embedding_layer.weights[0].shape)



Embedding을 진행할 문장: (1, 3)
Embedding된 문장: (1, 3, 100)
Embedding Layer의 Weight 형태: (64, 100)


# Embedding 레이어 주의사항
#### 기본적으로 딥러닝은 미분을 기반으로 동작한다. Embedding 레이어는 단어를 대응만 시켜줄 뿐이니 미분이 불가능하다.

#### 신경망 설계를 할 때 연산 결과에 Embedding 레이어에 연결시키는 것은 불가능

#### Embedding 레이어는 입력에 직접 연결되게 사용해야 한다는 것을 꼭 기억




In [ ]:
# 19-4. 순차적인 데이터! Recurrent 레이어 (1) RNN
sentence = "What time is it ?"
dic = {
    "is": 0,
    "it": 1,
    "What": 2,
    "time": 3,
    "?": 4}

print('RNN에 입력할 문장:', sentence)

sentence_tensor = tf.constant([[dic[word] for word in sentence.split()]])

print('Embedding을 위해 단어 매핑:', sentence_tensor.numpy())
print('입력 문장 데이터 형태:', sentence_tensor.shape)

embedding_layer = tf.keras.layers.Embedding(input_dim=len(dic), output_dim=100)
emb_out = embedding_layer(sentence_tensor)

print("\nEmbedding 결과:", emb_out.shape)
print("Embedding Layer의 Weight 형태:", embedding_layer.weights[0].shape)

rnn_seq_layer = \
tf.keras.layers.SimpleRNN(units=64, return_sequences=True, use_bias=False)
rnn_seq_out = rnn_seq_layer(emb_out)

print("\nRNN 결과 (모든 Step Output):", rnn_seq_out.shape)
print("RNN Layer의 Weight 형태:", rnn_seq_layer.weights[0].shape)

rnn_fin_layer = tf.keras.layers.SimpleRNN(units=64, use_bias=False)
rnn_fin_out = rnn_fin_layer(emb_out)

print("\nRNN 결과 (최종 Step Output):", rnn_fin_out.shape)
print("RNN Layer의 Weight 형태:", rnn_fin_layer.weights[0].shape)

RNN에 입력할 문장: What time is it ?
Embedding을 위해 단어 매핑: [[2 3 0 1 4]]
입력 문장 데이터 형태: (1, 5)

Embedding 결과: (1, 5, 100)
Embedding Layer의 Weight 형태: (5, 100)

RNN 결과 (모든 Step Output): (1, 5, 64)
RNN Layer의 Weight 형태: (100, 64)

RNN 결과 (최종 Step Output): (1, 64)
RNN Layer의 Weight 형태: (100, 64)


In [ ]:
# SimpleRNN 레이어의 return_sequences 인자를 조절
lstm_seq_layer = tf.keras.layers.LSTM(units=64, return_sequences=True, use_bias=False)
lstm_seq_out = lstm_seq_layer(emb_out)

print("\nLSTM 결과 (모든 Step Output):", lstm_seq_out.shape)
print("LSTM Layer의 Weight 형태:", lstm_seq_layer.weights[0].shape)

lstm_fin_layer = tf.keras.layers.LSTM(units=64, use_bias=False)
lstm_fin_out = lstm_fin_layer(emb_out)

print("\nLSTM 결과 (최종 Step Output):", lstm_fin_out.shape)
print("LSTM Layer의 Weight 형태:", lstm_fin_layer.weights[0].shape)


LSTM 결과 (모든 Step Output): (1, 5, 64)
LSTM Layer의 Weight 형태: (100, 256)

LSTM 결과 (최종 Step Output): (1, 64)
LSTM Layer의 Weight 형태: (100, 256)


In [ ]:
# 19-5. 순차적인 데이터! Recurrent 레이어 (2) LSTM

# 양방향 RNN
import tensorflow as tf

sentence = 'What time is it ?'
dic = {
    "is": 0,
    "it": 1,
    "What": 2,
    "time": 3,
    "?": 4}

sentence_tensor = tf.constant([[dic[word] for word in sentence.split()]])

embedding_layer = tf.keras.layers.Embedding(input_dim=len(dic), output_dim=100)
emb_out = embedding_layer(sentence_tensor)

print('입력 문장 데이터 형태:', emb_out.shape)

bi_rnn = \
tf.keras.layers.Bidirectional(
    tf.keras.layers.SimpleRNN(units=64, use_bias=False, return_sequences=True))

bi_out = bi_rnn(emb_out)

print("Bidirectional RNN 결과 (최종 Step Output):", bi_out.shape)


입력 문장 데이터 형태: (1, 5, 100)
Bidirectional RNN 결과 (최종 Step Output): (1, 5, 128)
